<!-- CONTENT -->
<div id="content">
    <div class="section-title">Tickets Fechados</div>

    <div class="table-card">
        <table class="table table-borderless mb-0">
            <thead>
                <tr>
                    <th>Nº Ticket</th>
                    <th>Entrada</th>
                    <th>Permanência</th>
                    <th>Valor</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tickets as $ticket): ?>
                    <tr>
                        <td><span class="badge-entrada"><?= $ticket['id'] ?></span></td>
                        <td>
                            <span class="badge-time">
                                <?= (new DateTime($ticket['entrada']))->format('d/m/Y H:i') ?>
                            </span>
                        </td>
                        <td>
                            <span class="badge-time"><?= $ticket['permanencia'] ?> Minutos</span>
                        </td>
                        <td>
                            <span class="badge-valor">R$ <?= number_format($ticket['valor'], 2, ',', '.') ?></span>
                        </td>
                        <td>
                            <button
                                class="btn btn-primary "
                                data-id="<?= $ticket['id'] ?>"
                                data-entrada="<?= $ticket['entrada'] ?>"
                                data-saida="<?= $ticket['saida'] ?>"
                                data-tempo="<?= $ticket['permanencia'] ?>"
                                data-valor="<?= $ticket['valor'] ?>">
                                Reabrir Ticket
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>