<!-- CONTENT -->
<div id="content">
    <div class="section-title">Tickets Fechados</div>

    <div class="table-card">
        <table class="table table-borderless mb-0">
            <thead>
                <tr>
                    <th>Entrada</th>
                    <th>Permanência</th>
                    <th>Valor</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><span class="badge-entrada">1624</span></td>
                    <td><span class="badge-time">16:32</span></td>
                    <td><span class="badge-time">00:43</span></td>
                    <td><button class="btn btn-danger ">R$ 8,00 · Fechar</button></td>
                </tr>
                <tr>
                    <td><span class="badge-entrada">1625</span></td>
                    <td><span class="badge-time">16:32</span></td>
                    <td><span class="badge-time">00:43</span></td>
                    <td><button class="btn btn-danger ">R$ 8,00 · Fechar</button></td>
                </tr>
                <tr>
                    <td><span class="badge-entrada">1626</span></td>
                    <td><span class="badge-time">16:32</span></td>
                    <td><span class="badge-time">00:43</span></td>
                    <td><button class="btn btn-danger ">R$ 8,00 · Fechar</button></td>
                </tr>
                <tr class="row-open">
                    <td><span class="badge-entrada">1627</span></td>
                    <td><span class="badge-time">16:32</span></td>
                    <td><span class="badge-time">00:43</span></td>
                    <td><button class="btn btn-primary">Aguardando</button></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>